# Generated by Django 4.2.13 on 2024-06-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_cliente_producto_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_producto',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='cliente_producto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_productos', to='Producto.producto'),
        ),
    ]
