# Generated by Django 4.2.13 on 2024-06-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_cliente_id_cliente_producto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_producto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Producto.producto'),
        ),
    ]
